workflows:
  build-android:
    name: Build Android APK (React Native)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: latest
      java: 17
      npm: latest
      groups:
        - android_signing
    cache:
      cache_paths:
        - $HOME/.npm
        - android/.gradle
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Install Android dependencies
        script: cd android && ./gradlew dependencies && cd ..
      - name: Build Android Release APK
        script: cd android && ./gradlew assembleRelease && cd ..
    artifacts:
      - android/app/build/outputs/**/*.apk

  build-ios:
    name: Build iOS IPA (React Native)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: latest
      npm: latest
      cocoapods: default
      groups:
        - ios_signing
    cache:
      cache_paths:
        - $HOME/.npm
        - ios/Pods
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Install CocoaPods
        script: cd ios && pod install && cd ..
      - name: Build iOS Release IPA
        script: cd ios && xcodebuild -workspace MyJantesexpoApp.xcworkspace -scheme MyJantesexpoApp -configuration Release -archivePath $
